### ISSUE TITLE
Error with numpy 1.24

### ISSUE THREAD

**Issue by jkitchin** [aspuru-guzik-group/gryffin#29]
This line `params = gryffin.recommend(observations=observations)[0]` eventually fails with 

`AttributeError: module 'numpy' has no attribute 'float'`

The issue is np.float was deprecated, and removed (https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations).

It works fine with numpy 1.23.5.

A clumsy fix in a script is: `np.float = float`.
